### ISSUE TITLE
cv2.findContours ValueError

### ISSUE THREAD

**Issue by alprnbg** [lony/python-opencv-crop#2]
Library = OpenCV 4.0

In crop.py file cv2.findContours function gives error (line 69). 
`ValueError: not enough values to unpack (expected 3, got 2)` <br>
The reason is that cv2.findContours no more returns 3 values, instead it returns 2 values. Line should be changed to 
`contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)`

**Comment by lony** [comment]
Hello @alprnbg , I did this a while back and never tried it with 4.0. If you like could you push a PR with your fixes?

**Comment by alprnbg** [comment]
Of course, I would like to contribute.

**Comment by lony** [comment]
Solved by https://github.com/lony/python-opencv-crop/pull/3
